# Copy this to your repo's .github/workflows/
name: DiffGuard PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  diffguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ostehost/diffguard@main
        with:
          python-version: "3.11"
          post-comment: "true"
